name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please detail what happened and its situation. Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.3.4 (Default)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What os are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: extensions
    attributes:
      label: Using extensions
      description: Please list the extensions you are using with youtube-manual-ad-remover.
